## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Reuse City"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Reuse City is a studio dedicated to applied research, service design and technology development in the fields of circular economy, right to repair, and zero waste."
  logo = "images/reuse-city.png"
  favicon = true

[Params.social]
  github = "https://github.com/reuse-city/"
  twitter = "https://x.com/reuse_city"
  instagram = "https://www.instagram.com/reuse.city"
  linkedin = "https://www.linkedin.com/company/reuse-city/"
  email = "felipefonseca+reusecity@gmail.com"
  orcid = "https://orcid.org/0000-0002-4764-7069"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]